---
"@poyro/vitest": patch
"@poyro/docs": patch
---

Running the same expect twice in a row led to different outcomes, when it should not. Here is a minimal reproducing example:

```javascript
import { expect, it } from "vitest";

it("should be true", async () => {
  // This is some output generated by an LLM, the way you get it
  // is totally up to you
  const llmOutput = "Hello, world!";

  await expect(llmOutput).toFulfillCriterion("Says hello"); // passed
  await expect(llmOutput).toFulfillCriterion("Says hello"); // failed
}, 10000); // Increase the timeout as needed with the third argument
```

Upgrading to node llama 3 beta 36 resolves the problem. Node llama is in an unstable state because its in beta, but version 3 provides the functionality needed for Poyro so we're biting that cost for now.
